version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volunme:/home/app/web/static
    ports:
      - "9003:80"
    depends_on:
      - django

  django:
    build: ./mysite
    volumes:
      - static_volunme:/usr/src/app/static
    expose:
      - "8000"
    depends_on:
      - db
      - kafka

  scrapyd:
    build: ./crawler
    volumes:
      - ./crawler:/usr/src/app
      - ./crawler/logs:/logs
      - ./crawler/dbs:/dbs
      - ./crawler/scrapyd.conf:/etc/scrapyd/scrapyd.conf
    ports:
      - "6800:6800"
    depends_on:
      - kafka

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  mongo_data:
  static_volunme:
