# Generated by Django 4.2.7 on 2023-11-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_stock_current_price_stock_high_price_stock_low_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='opening_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='prev_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
