# Generated by Django 4.2.7 on 2023-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_stock_opening_price_stock_prev_price_stock_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
