# Generated by Django 4.2.7 on 2023-11-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_balance',
            field=models.IntegerField(default=0),
        ),
    ]
