# Generated by Django 2.0.13 on 2021-01-03 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_stockdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdingstock',
            old_name='count',
            new_name='cnt',
        ),
        migrations.RemoveField(
            model_name='holdingstock',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='code',
        ),
        migrations.AlterField(
            model_name='holdingstock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
