# Generated by Django 2.0.13 on 2021-01-05 11:40

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210103_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingstock',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_stock',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.StockData'),
        ),
    ]
