# Generated by Django 3.1.5 on 2021-01-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_stockdata_pre_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='high_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='low_price',
            field=models.IntegerField(default=0),
        ),
    ]
