# Generated by Django 3.1.5 on 2021-01-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210109_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['time']},
        ),
    ]
