# Generated by Django 3.1.5 on 2021-01-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210113_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingstock',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
